### ISSUE TITLE
Need to access the string in print()

### ISSUE THREAD

**Issue by gapolli** [VictorGom3s/Awful-Text-Editor#5]

**Comment by VictorGom3s** [comment]
Fiz um commit agora e acredito que a função 'print' está praticamente correta, porém só o primeiro caractere da string está sendo impresso. O problema, acredito eu, está na função 'insertText( )', creio que deveríamos reescreve-la.

**Comment by VictorGom3s** [comment]
Adicionei alguns printfs no código que ajudam a entender o fluxo do programa. Vamos mante-los por esquanto.

**Comment by VictorGom3s** [comment]
Função insertText e print corrigidas. Agora estão funcionando corretamente.
